"""
DocumentAgent – Processes, summarises, and generates business documents.
Handles extraction, classification, and structured output from text.
"""

from datetime import datetime
from typing import Any


class DocumentAgent:
    name = "DocumentAgent"
    description = "AI agent for document processing, summarisation, and structured data extraction."
    capabilities = [
        "document_summarisation",
        "data_extraction",
        "report_generation",
        "document_classification",
        "content_analysis",
    ]

    def __init__(self):
        self.status = "idle"
        self.last_run: datetime | None = None
        self._processed_count = 0

    # ------------------------------------------------------------------
    def process_document(self, document: dict[str, Any]) -> dict[str, Any]:
        """Parse a document and return structured metadata."""
        self.status = "active"
        self.last_run = datetime.utcnow()
        self._processed_count += 1

        text = document.get("content", "")
        word_count = len(text.split())
        doc_type = document.get("type", "unknown")

        classification = self._classify(text, doc_type)

        self.status = "idle"
        return {
            "agent": self.name,
            "task": "process_document",
            "timestamp": datetime.utcnow().isoformat(),
            "document_id": document.get("id", f"DOC-{self._processed_count}"),
            "word_count": word_count,
            "type": doc_type,
            "classification": classification,
            "processed": True,
        }

    def summarise(self, text: str, max_sentences: int = 3) -> dict[str, Any]:
        """Return an extractive summary (first N sentences as a proxy)."""
        self.status = "active"
        self.last_run = datetime.utcnow()

        sentences = [s.strip() for s in text.replace("!", ".").replace("?", ".").split(".") if s.strip()]
        summary = ". ".join(sentences[:max_sentences]) + ("." if sentences else "")

        self.status = "idle"
        return {
            "agent": self.name,
            "task": "summarisation",
            "timestamp": datetime.utcnow().isoformat(),
            "original_sentences": len(sentences),
            "summary_sentences": min(max_sentences, len(sentences)),
            "summary": summary,
        }

    def extract_data(self, text: str, fields: list[str]) -> dict[str, Any]:
        """Attempt to locate field values within unstructured text."""
        self.status = "active"
        self.last_run = datetime.utcnow()

        extracted: dict[str, str | None] = {}
        lines = text.lower().split("\n")
        for field in fields:
            match = next((line for line in lines if field.lower() in line), None)
            extracted[field] = match.strip() if match else None

        self.status = "idle"
        return {
            "agent": self.name,
            "task": "data_extraction",
            "timestamp": datetime.utcnow().isoformat(),
            "fields_requested": fields,
            "extracted": extracted,
            "extraction_rate_pct": round(sum(1 for v in extracted.values() if v) / max(len(fields), 1) * 100, 1),
        }

    def generate_report(self, template: str = "standard", context: dict[str, Any] | None = None) -> dict[str, Any]:
        """Generate a structured business report based on a template."""
        self.status = "active"
        self.last_run = datetime.utcnow()
        ctx = context or {}

        sections = {
            "executive_summary": f"Report generated by {self.name} on {datetime.utcnow().date()}.",
            "key_findings": ctx.get("findings", ["No findings provided."]),
            "recommendations": ctx.get("recommendations", ["No recommendations provided."]),
            "next_steps": ctx.get("next_steps", ["Review and distribute report."]),
        }

        self.status = "idle"
        return {
            "agent": self.name,
            "task": "report_generation",
            "timestamp": datetime.utcnow().isoformat(),
            "template": template,
            "report": sections,
        }

    # ------------------------------------------------------------------
    def _classify(self, text: str, doc_type: str) -> str:
        keywords = {
            "financial": ["revenue", "budget", "profit", "loss", "invoice"],
            "legal": ["agreement", "contract", "clause", "liability", "party"],
            "operational": ["process", "workflow", "SLA", "incident", "KPI"],
            "strategic": ["vision", "mission", "goal", "objective", "market"],
        }
        text_lower = text.lower()
        for category, words in keywords.items():
            if any(w in text_lower for w in words):
                return category
        return doc_type if doc_type != "unknown" else "general"

    def get_status(self) -> dict[str, Any]:
        return {
            "agent": self.name,
            "description": self.description,
            "capabilities": self.capabilities,
            "status": self.status,
            "last_run": self.last_run.isoformat() if self.last_run else None,
            "documents_processed": self._processed_count,
        }
